# Dual Encoder: SigLIP2 + DINOv3
root_path: ''

load_cache: False
load_pre_feat: False

search_hp: True
search_scale: [10, 10]
search_step: [200, 20]
init_beta: 1
init_alpha: 1.17

dataset: 'food101'
shots: 16
use_dual_encoder: True
siglip_model: 'google/siglip2-base-patch16-224'
dinov3_model: 'MFY111/dinov3-vits16'

augment_epoch: 10
train_epoch: 20
